### ISSUE TITLE
ToDo list design meeting Feb13

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#7]
This is the list of some agreements from the design meeting:

- [x] The mockup for the one block/two blocks scene button was accepted, but the background has to be improved. Develop them with the common code. The panel is ready to be implemented! it's ok not to add the min and max values to the slide bars

![image](https://user-images.githubusercontent.com/26031501/74488268-439aee80-4e87-11ea-84f3-c64718e6831e.png)

- [x] Put back the units in the red/blue markers in the Density readout
![image](https://user-images.githubusercontent.com/26031501/74488321-7349f680-4e87-11ea-994e-2c2e17be167b.png)

- [x] Change the mass and volume labels to not a bold font.

- [x] Snap the slide bars (mass and volume) to 0.1

Open question:
alignment of the slide bars
![image](https://user-images.githubusercontent.com/26031501/74488421-bf953680-4e87-11ea-9986-9848b2980053.png)

**Comment by jonathanolson** [comment]
> Change the mass and volume labels to not a bold font.

I think it was previous decided that the "title font" would be used here, which is also used e.g. as the "Density Readout (kg/L)". Should all of those be un-bolded, or should the mass/volume labels be different (and NOT used that shared font)?

**Comment by DianaTavares** [comment]
What I mean by "mass and volume labels" are the ones that indicate the values of these variables in the pool and in the blocks. You already change them to un-bolded (screenshot from slack).  Amanda, Kathy and I agreed that un-bolded look better. 

<img width="386" alt="Screen Shot 2020-02-18 at 11 33 13 AM" src="https://user-images.githubusercontent.com/26031501/76023256-6cdef580-5eee-11ea-86d2-ca6ca506d78b.png">

<img width="384" alt="Screen Shot 2020-02-18 at 11 32 22 AM" src="https://user-images.githubusercontent.com/26031501/76023252-6b153200-5eee-11ea-87fa-d5befb72769d.png">

**Comment by jonathanolson** [comment]
These have been applied in https://phet-dev.colorado.edu/html/density/1.0.0-dev.4/phet/density_en_phet.html, how does that look?

**Comment by DianaTavares** [comment]
I looks very well!
just the panels need to be the same color, and the density readout is darker than the other panels 
![image](https://user-images.githubusercontent.com/26031501/76262570-4f799680-6222-11ea-9bdf-ad3937b4af09.png)

**Comment by jonathanolson** [comment]
Handled the density readout background color in the above commit

**Comment by DianaTavares** [comment]
In the sim in phettest I still seeing the Density Readout darker that the panel (is it only my perception?) 

![image](https://user-images.githubusercontent.com/26031501/76341672-fc0b5500-62c2-11ea-9cba-82c4c28dc091.png)

Also, in some situations, the bouncing of the block looks strange. For example, in this gift, the styrofoam block doesn't stop bouncing:

![density](https://user-images.githubusercontent.com/26031501/76341976-6a501780-62c3-11ea-97c8-5564fc6463e5.gif)

**Comment by jonathanolson** [comment]
> In the sim in phettest I still seeing the Density Readout darker that the panel (is it only my perception?)

Might be cached. I'm updating repos on phet-test, hopefully that will fix it for you.

> Also, in some situations, the bouncing of the block looks strange. For example, in this gift, the styrofoam block doesn't stop bouncing:

Agreed, I need to investigate how to handle this with the physics model.

**Comment by jonathanolson** [comment]
I believe this bouncing issue should now be fixed in master. Can you see how the physics behaves?

**Comment by DianaTavares** [comment]
it looks great! thanks!!
